import type { InferGetServerSidePropsType, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { gql } from '@apollo/client';
import { graphqlClient } from './_app';
import { ReactNode } from 'react';

export const LOGIN = gql`
    mutation {
        login(email: "Pat_Schiller@hotmail.com", password: "secret") {
            firstname
            lastname
            phoneNumber
            email
        }
    }
`;

export async function getServerSideProps(context: any) {
    const { data } = await graphqlClient.mutate({ mutation: LOGIN });

    return {
        props: { user: data.login },
    };
}

export default function Home(props: InferGetServerSidePropsType<typeof getServerSideProps> & { children?: ReactNode }) {
    return (
        <div className={styles.container}>
            <div>{JSON.stringify(props.user, null, 4)}</div>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>
                </div>
            </main>
        </div>
    );
}
